# docker-compose-dev.yml: for dev environment only!
version: '2'

services:
  php-apache:
    build: ./docker/dev
    container_name: printservice_api_dev
    ports:
      - 80:80
    volumes:
      # main volume
      - .:/var/www/html:rw
      - ./tmp:/tmp:rw
      # others
      - ./docker/ext-apcu.ini:/usr/local/etc/php/conf.d/ext-acpu.ini:ro
      - ./docker/01-fixing-apache-permissions:/etc/fix-attrs.d/01-fixing-apache-permissions:rw
      - ./docker/run:/etc/services.d/apache/run:rw
      # ignored folders
      - /var/www/html/bin
      - /var/www/html/docker
    restart: unless-stopped
    networks:
      - dev

networks:
  dev: {}
